using System.Numerics;

namespace JolieCat3D.Core.Geometry
{
    /// <summary>
    /// Extracts a <see cref="Mesh"/>'s own UV-space wireframe - one line segment per
    /// triangle EDGE (not per triangle - a shared edge between two adjacent triangles
    /// is drawn twice, once per triangle, the same "just draw every triangle's own 3
    /// edges" simplicity <c>Engine.Rendering.WireframeVisualFactory</c> already uses for
    /// the 3D wireframe overlay, rather than deduplicating shared edges first) - the
    /// actual "which lines to draw" math behind the UV Map Visualizer
    /// (<c>JolieCat3D.UI.UVVisualizerWindow</c>), kept here so it's testable with no WPF
    /// runtime at all, the same Core/UI split every other geometry algorithm in this
    /// project already follows.
    /// </summary>
    public static class UVWireframe
    {
        /// <summary>Every triangle's own 3 edges, as pairs of raw UV coordinates (see
        /// <see cref="Vertex.UV"/> - the same values <c>UVProjector</c> writes and
        /// <c>Engine.Geometry.MaterialFactory</c>'s own texture sampling reads). Not
        /// clamped/wrapped to [0,1] here - a mesh with UVs authored (or generated by a
        /// custom UV projection) outside that range is a real, valid case a caller may
        /// still want to SEE plotted (a point outside the unit square shows exactly
        /// where the texture actually tiles/clips), so this reports the raw values and
        /// leaves any clamping/scaling to whoever draws them.</summary>
        public static IEnumerable<(Vector2 A, Vector2 B)> GetEdges(Mesh mesh)
        {
            ArgumentNullException.ThrowIfNull(mesh);

            foreach (var face in mesh.GetRenderFaces())
            {
                var a = mesh.Vertices[face.A].UV;
                var b = mesh.Vertices[face.B].UV;
                var c = mesh.Vertices[face.C].UV;

                yield return (a, b);
                yield return (b, c);
                yield return (c, a);
            }
        }
    }
}
