<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>CatSuite.Installer</AssemblyName>
		<RootNamespace>CatSuite.Installer</RootNamespace>
		<AssemblyVersion>1.2.0.0</AssemblyVersion>
		<FileVersion>1.2.0.0</FileVersion>
		<Version>1.2.0</Version>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
	  <PackageReference Include="System.Text.Json" Version="9.0.10" />
	</ItemGroup>

</Project>