<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AsmodayCat.Service-e6614c0c-dab7-43a8-b934-5b00b98c0897</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsmodayCat.Agent\AsmodayCat.Agent.csproj" />
    <ProjectReference Include="..\AsmodayCat.Core\AsmodayCat.Core.csproj" />
    <ProjectReference Include="..\AsmodayCat.Network\AsmodayCat.Network.csproj" />
    <ProjectReference Include="..\ClassLibrary1\AsmodayCat.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="IpcServer\" />
  </ItemGroup>
</Project>
