<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>AsmodayCat.UI</RootNamespace>
    <ApplicationIcon>Assets\AC.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
  </ItemGroup>

  <ItemGroup>
    <!-- Explicitly mark the icon as a WPF Resource so pack URIs resolve in XAML -->
    <Resource Include="Assets\AC.ico"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\AsmodayCat.Shared.csproj" />
  </ItemGroup>

</Project>
