<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-JolieCat.Service-8b9c5173-5ffb-4e4b-a696-c036ed026439</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JolieCat.Core\JolieCat.Core.csproj" />
    <ProjectReference Include="..\JolieCat.Shared\JolieCat.Shared.csproj" />
  </ItemGroup>
</Project>
